CREATE TABLE bowling_ball (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key VARCHAR(1024) NOT NULL UNIQUE,
    source_url VARCHAR(1024) NOT NULL,
    source_id VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(255),
    coverstock_type VARCHAR(255),
    core_type VARCHAR(255)
);
CREATE TABLE bowling_ball_weight (
    ball_id BIGINT NOT NULL REFERENCES bowling_ball(id) ON DELETE CASCADE,
    weight INTEGER NOT NULL CHECK (weight BETWEEN 1 AND 16),
    PRIMARY KEY (ball_id, weight)
);
CREATE INDEX bowling_ball_weight_weight_idx ON bowling_ball_weight(weight);
