CREATE TABLE tournament (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL UNIQUE,
    source_url VARCHAR(1024) NOT NULL,
    title VARCHAR(1000) NOT NULL,
    venue_name VARCHAR(255),
    city VARCHAR(255),
    region VARCHAR(64),
    address VARCHAR(1000),
    start_date DATE,
    end_date DATE,
    date_text VARCHAR(255),
    entry_price_from NUMERIC(10,2),
    currency_symbol VARCHAR(8),
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (entry_price_from IS NULL OR entry_price_from >= 0),
    CHECK (start_date IS NULL OR end_date IS NULL OR end_date >= start_date)
);
CREATE TABLE tournament_entry_fee (
    tournament_id BIGINT NOT NULL REFERENCES tournament(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    event_name VARCHAR(500) NOT NULL,
    amount NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
    symbol VARCHAR(8) NOT NULL,
    PRIMARY KEY (tournament_id, position)
);
CREATE INDEX tournament_dates_idx ON tournament(end_date, start_date);
CREATE INDEX tournament_location_idx ON tournament(region, venue_name);
